server:
  port: 8888
security:
  user:
    name: user
    password: 123456
management:
  security:
    enabled: false
#Registering with Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
#Apache Kafka Binder for bus-kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 112.74.16.8:9092
          #defaultBrokerPort: 9092
          zkNodes: 112.74.16.8:2181
          #defaultZkPort: 2181
    # enable /trace endpoint
    bus:
      trace:
        enabled: true