
spring:
#Apache Kafka Binder for bus-kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.40.18:9092,192.168.40.19:9092
          #defaultBrokerPort: 9092
          zkNodes: 192.168.40.17:2181/dev
          #defaultZkPort: 2181
  thymeleaf.cache: false
logging.level.org.springframework.security: DEBUG
# custom properties
config-client2-welcome: Test1, message updated1
