spring:
  profiles: test
#Apache Kafka Binder for bus-kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.100:9092
          #defaultBrokerPort: 9092
          zkNodes: 192.168.1.100:2181
          #defaultZkPort: 2181
  thymeleaf.cache: false
logging.level.org.springframework.security: DEBUG
# custom properties
config-client2-welcome: hello, welcome to my test world

